apiVersion: v2
name: test-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: external-secrets
    version: "0.9.11"
    repository: "https://charts.external-secrets.io"
